---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: list files
        run: ls -a /home/runner/work/github-actions-test/github-actions-test
      # fix backwards incompatibilities in template
      #- name: Fix Template
      #  uses: hashicorp/packer-github-actions@master
      #  with:
      #    command: fix
#
      ## validate templates
      #- name: Validate Template
      #  uses: hashicorp/packer-github-actions@master
      #  with:
      #    command: validate
      #    arguments: -syntax-only
      #    target: ../gha-base-ami/packer/packer.json

      # build artifact
      - name: Build Artifact
        uses: ./.github/actions/packer-github-actions
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ./gha-base-ami/packer/packer.json
        env:
          PACKER_LOG: 1
